<h2 style="margin-top: 1rem;">Edit Deck Form</h2>

<p><?php echo $this->flash->output() ?></p>

<div class="jumbotron" style="padding: 2rem;  width: 50%;">
    <?php echo $this->tag->form("deck/edit/submit"); ?>

        <p>
            <label for="title">Deck Title</label>
            <?php echo $form->render("title"); ?>
        </p>

        <p>
            <?php echo $form->render("save"); ?>
        </p>

    </form>
</div>

<?php 
    echo $this->tag->linkTo([
        "/user/profile",
        'Back',
        "class" => "btn btn-secondary",
    ]);
?>