<h2>Edit Deck Form</h2>

<p><?php echo $this->flash->output() ?></p>

<?php echo $this->tag->form("deck/edit/submit"); ?>

    <p>
        <label for="title">Deck Title</label>
        <?php echo $form->render("title"); ?>
    </p>

    <p>
        <?php echo $form->render("save"); ?>
    </p>

</form>

<?php 
    echo $this->tag->linkTo([
        "/user/profile",
        'Back',
        "class" => "btn btn-secondary",
    ]);
?>