<head>
  <title>Learn</title>
  <style>
    #LearnSpace {
        display: flex;
        align-items: center;
        justify-content: center 
        }
    }
  </style>
</head>

<div class="container">
    <?php if ($currentCard) { ?>

        <section id="LearSpace" class="team-section text-center my-5">
            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-md-0 mb-4">
                <!--Card-->
                <div class="card front">
                    <div class="card-body">
                    <!--Front-->
                    <h4 class="font-weight-bold mb-4"><?php echo $currentCard->frontside;?></h4>
                    <hr>
                    <!--Reveal-->
                    <?php echo $this->tag->linkTo([
                        "/user/profile/deck/".$currentCard->deck_id."/learn/".$currentCard->id."/reveal",
                        'Reveal',
                        "class" => "btn btn-light btn-lg",
                        "style" => "text-align: center;",
                        ]);
                    ?>
                    </div>
                </div>
                <!--Card-->
                </div>
                <!--Grid column-->
        </section>
        
        <?php
            // echo $currentCard->frontside;
            // echo "<br>";
            // echo $currentCard->time;
        ?>

<?php }else{  ?>
        <section id="RevealSpace" class="team-section text-center my-5">
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-md-0 mb-4">
            <!--Card-->
            <div class="card front">
                <!--Avatar-->
                <div class="card-body">
                <!--Name-->
                <h4 class="font-weight-bold mb-4">Good job!</h4>
                <p>you've studied all today's cards on this deck</p>
                <hr>
                <!--Quotation-->
                <?php echo $this->tag->linkTo([
                        "/user/profile/deck/".$this->session->get('DECK_ON'),
                        'Back',
                        "class" => "btn btn-primary btn-lg",
                        "style" => "text-align: center;",
                    ]);
                 ?>
                </div>
            </div>
            <br>
            <?php
                // echo $this->tag->linkTo([
                //     "/user/profile/deck/".$this->session->get('DECK_ON'),
                //     'Back',
                //     "class" => "btn btn-primary btn-lg",
                //     "style" => "text-align: center;",
                // ]);
            ?>
            <!--Card-->
            </div>
            <!--Grid column-->
    </section>
    <?php } ?>
</div>

<script>
    // function reveal() {
    //     var x = document.getElementById("asd-<?php echo $cards2playData[$i]->id; ?>-asd");
    //     if (x.style.display === "none") {
    //         x.style.display = "block";
    //     } else {
    //         x.style.display = "none";
    //     }
    // }
</script>