<head>
  <title>Reveal</title>
  <style>
    #RevealSpace {
        margin-left: auto;
        margin-right: auto;
        width: 60em
    }
  </style>
</head>

<div class="container">
    <section id="RevealSpace" class="team-section text-center my-5">
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-md-0 mb-4">
            <!--Card-->
            <div class="card front">
                <!--Avatar-->
                <div class="card-body">
                <!--Name-->
                <h4 class="font-weight-bold mb-4"><?php echo $currentCard->frontside;?></h4>
                <hr>
                <!--Quotation-->
                <p class="dark-grey-text mt-4"><i class="fas fa-quote-left pr-2"></i><?php echo $currentCard->backside;?></p>
                </div>
            </div>
            <!--Card-->
            </div>
            <!--Grid column-->
    </section>
    <?php if ($currentCard) { ?>

        <header>
        <?php
            echo $currentCard->frontside;
            echo "<br>";
            echo $currentCard->time;
            echo "<br>";
            echo $currentCard->backside;
            
        ?>
        </header>

        <article>
        <?php echo $this->tag->form("/user/profile/deck/".$currentCard->deck_id."/learn/".$currentCard->id."/reveal/difftime"); 

            $diff = 3;
            $time = 0;
            echo "<input type='hidden'  name='diff'  value=" . $diff . ">";
            echo "<input type='hidden'  name='time'  value=" . $time . ">";
            echo "<input type='hidden'  name='card_id' value=" . $currentCard->id . ">";
        ?>
        <?php echo $this->tag->submitButton("Again"); ?>

        </form>

        <?php echo $this->tag->form("/user/profile/deck/".$currentCard->deck_id."/learn/".$currentCard->id."/reveal/difftime"); 
            $diff = 2;
            $time = 1;
            echo "<input type='hidden'  name='diff'  value=" . $diff . ">";
            echo "<input type='hidden'  name='time'  value=" . $time . ">";
            echo "<input type='hidden'  name='card_id' value=" . $currentCard->id . ">";
        ?>
        <?php echo $this->tag->submitButton("Good"); ?>

        </form>

        <?php echo $this->tag->form("/user/profile/deck/".$currentCard->deck_id."/learn/".$currentCard->id."/reveal/difftime"); 
            $diff = 1;
            $time = 2;
            echo "<input type='hidden'  name='diff'  value=" . $diff . ">";
            echo "<input type='hidden'  name='time'  value=" . $time . ">";
            echo "<input type='hidden'  name='card_id' value=" . $currentCard->id . ">";
        ?>
        <?php echo $this->tag->submitButton("Easy"); ?>

        </form>
        </article>

    <?php }else{
        echo "habis";
    } ?>
</div>