<head>
  <title>Reveal</title>
  <style>
    #RevealSpace {
        display: flex;
        align-items: center;
        justify-content: center 
    }
  </style>
</head>

<div class="container">
    
    <?php if ($currentCard) { ?>

        <section id="RevealSpace" class="team-section text-center my-5">
            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-md-0 mb-4">
                <!--Card-->
                <div class="card front">
                    <div class="card-body">
                    <!--Front-->
                    <h4 class="font-weight-bold mb-4"><?php echo $currentCard->frontside;?></h4>
                    <hr>
                    <!--Back-->
                    <p class="dark-grey-text mt-4"><i class="fas fa-quote-left pr-2"></i><?php echo $currentCard->backside;?></p>
                    </div>
                </div>
                <!--Card-->
                </div>
                <!--Grid column-->
        </section>

        <header>
        <?php
            // echo $currentCard->frontside;
            // echo "<br>";
            // echo $currentCard->time;
            // echo "<br>";
            // echo $currentCard->backside;
            
        ?>
        </header>

        <section id="GoButtons" class="team-section text-center my-5">
        <!--Grid row-->
        <div class="row text-center">

        <!--Grid column-->
        <div class="col-md-4 mb-md-0 mb-5">

        <div class="testimonial">
        <?php echo $this->tag->form("/user/profile/deck/".$currentCard->deck_id."/learn/".$currentCard->id."/reveal/difftime"); 

            $diff = 3;
            $time = 0;
            echo "<input type='hidden'  name='diff'  value=" . $diff . ">";
            echo "<input type='hidden'  name='time'  value=" . $time . ">";
            echo "<input type='hidden'  name='card_id' value=" . $currentCard->id . ">";
            echo "<td >"." <input type='submit' name=control value='Again' style='background-color: #f44336;font-size:20px;border:none' class='submit'> "." </td>";
            ?>
        </form>
            
        </div>

        </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-4 mb-md-0 mb-5">

            <div class="testimonial">
            <?php echo $this->tag->form("/user/profile/deck/".$currentCard->deck_id."/learn/".$currentCard->id."/reveal/difftime"); 

                $diff = 2;
                $time = 1;
                echo "<input type='hidden'  name='diff'  value=" . $diff . ">";
                echo "<input type='hidden'  name='time'  value=" . $time . ">";
                echo "<input type='hidden'  name='card_id' value=" . $currentCard->id . ">";
                echo "<td >"." <input type='submit' name=control value='Good' style='background-color: #008CBA;font-size:20px;border:none' class='submit'> "." </td>";
                ?>

            </form>
                
            </div>

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-4">

            <div class="testimonial">
            <?php echo $this->tag->form("/user/profile/deck/".$currentCard->deck_id."/learn/".$currentCard->id."/reveal/difftime"); 

                $diff = 1;
                $time = 2;
                echo "<input type='hidden'  name='diff'  value=" . $diff . ">";
                echo "<input type='hidden'  name='time'  value=" . $time . ">";
                echo "<input type='hidden'  name='card_id' value=" . $currentCard->id . ">";
                echo "<td >"." <input type='submit' name=control value='Easy' style='background-color: #4CAF50;font-size:20px;border:none' class='submit'> "." </td>";
                ?>

            </form>
                
            </div>

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->
    </section>

    <?php }else{
        echo "habis";
    } ?>
</div>