<!-- <div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>You're now flying with Phalcon. Great things are about to happen!</p>

<p>This page is located at <code>views/index/index.phtml</code></p> -->

<h1>Welcome to FLASH</h1>

<h3>Lets Learn!</h3>

<?php

    echo $this->tag->linkTo([
        'user/register',
        'Register here!',
        "class" => "btn btn-primary",
        "style" => "margin-top: 5rem;",
    ]);

    echo $this->tag->linkTo([
        'user/login',
        'Login here!',
        "class" => "btn btn-primary",
        "style" => "margin-top: 5rem; margin-left: 5rem;",
    ]);
?>