<div class="container">
    <h2 style="margin-top: 1rem;">Register here!</h2>

    <p><?php echo $this->flash->output() ?></p>

    <div class="jumbotron" style="padding: 2rem; width: 50%;">
        <?php echo $this->tag->form("user/register/submit"); ?>

            <div class="form-group" style="width: 90%;">
                <label for="name">Name</label>
                <?php echo $form->render("name"); ?>
            </div>

            <div class="form-group" style="width: 90%;">
                <label for="email">E-Mail</label>
                <?php echo $form->render("email"); ?>
            </div>

            <div class="form-group" style="width: 90%;">
                <label for="password">Password</label>
                <?php echo $form->render("password"); ?>
            </div>

            <div class="form-group" style="width: 90%;">
                <label for="password_confirm">Confirm Password</label>
                <?php echo $form->render("password_confirm"); ?>
            </div>

            <div class="form-group" style="margin-top: 2rem;">
                <?php echo $form->render("submit"); ?>
            </div>

        </form>

        <p style="margin-top: 2rem;">Already have an account? Login <a href="login">here!</a></p>

    </div>
</div>