<h2>Create Card Form</h2>

<p><?php echo $this->flash->output() ?></p>

<?php echo $this->tag->form("/card/create/submit"); ?>

    <p>
        <label for="frontside">Front Side</label>
        <?php echo $form->render("frontside"); ?>
    </p>

    <p>
        <label for="backside">Back Side</label>
        <?php echo $form->render("backside"); ?>
    </p>

    <p>
        <label for="difficulty">Difficulty</label>
        <?php echo $form->render("difficulty"); ?>
    </p>

    <p>
        <?php echo $form->render("create"); ?>
    </p>

</form>