<h2 style="margin-top: 1rem;">Create Card Form</h2>

<p><?php echo $this->flash->output() ?></p>

<div class="jumbotron" style="padding: 2rem;  width: 50%;">
    <?php echo $this->tag->form("/card/create/submit"); ?>

        <p>
            <label for="frontside">Front Side</label>
            <?php echo $form->render("frontside"); ?>
        </p>

        <p>
            <label for="backside">Back Side</label>
            <?php echo $form->render("backside"); ?>
        </p>

        <p>
            <label for="difficulty">Difficulty</label>
            <?php echo $form->render("difficulty"); ?>
        </p>

        <p>
            <?php echo $form->render("create"); ?>
        </p>

    </form>
</div>

<?php 
    echo $this->tag->linkTo([
        "/user/profile/deck/".$this->session->get('DECK_ON'),
        'Back',
        "class" => "btn btn-secondary",
        "style" => "margin: 0pt;",
    ]);

?>